# cloudflare_gen.py
# Cloudflare Worker integration for domain generation
import httpx
import os
from main import logger, get_host

CLOUDFLARE_API_BASE = "https://api.cloudflare.com/client/v4"

async def create_dns_record(zone_id: str, api_token: str, subdomain: str, domain: str, target: str):
    """Create a DNS record via Cloudflare API"""
    async with httpx.AsyncClient() as client:
        url = f"{CLOUDFLARE_API_BASE}/zones/{zone_id}/dns_records"
        headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json"
        }
        data = {
            "type": "A",
            "name": f"{subdomain}.{domain}",
            "content": target,
            "ttl": 120,
            "proxied": True
        }
        response = await client.post(url, headers=headers, json=data)
        return response.json()

async def delete_dns_record(zone_id: str, api_token: str, record_id: str):
    """Delete a DNS record via Cloudflare API"""
    async with httpx.AsyncClient() as client:
        url = f"{CLOUDFLARE_API_BASE}/zones/{zone_id}/dns_records/{record_id}"
        headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json"
        }
        response = await client.delete(url, headers=headers)
        return response.json()

async def list_dns_records(zone_id: str, api_token: str, domain: str):
    """List DNS records for a domain"""
    async with httpx.AsyncClient() as client:
        url = f"{CLOUDFLARE_API_BASE}/zones/{zone_id}/dns_records"
        headers = {
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json"
        }
        params = {"name": domain}
        response = await client.get(url, headers=headers, params=params)
        return response.json()

def generate_worker_script(subdomain: str, domain: str, target: str) -> str:
    """Generate a Cloudflare Worker script for domain proxying"""
    return f"""
// Cloudflare Worker for {subdomain}.{domain}
// Generated by CBeeNet Gateway

addEventListener('fetch', event => {{
  event.respondWith(handleRequest(event.request))
}})

async function handleRequest(request) {{
  const url = new URL(request.url)
  const targetUrl = new URL('https://{target}' + url.pathname + url.search)
  
  const headers = new Headers(request.headers)
  headers.set('Host', '{target}')
  headers.set('X-Forwarded-Host', url.host)
  headers.set('X-Forwarded-Proto', 'https')
  
  const response = await fetch(targetUrl.toString(), {{
    method: request.method,
    headers: headers,
    body: request.body
  }})
  
  const responseHeaders = new Headers(response.headers)
  responseHeaders.set('Access-Control-Allow-Origin', '*')
  
  return new Response(response.body, {{
    status: response.status,
    statusText: response.statusText,
    headers: responseHeaders
  }})
}}
"""
