# pages.py — CBee Gateway

LOGIN_HTML = r'''<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CBee · Login</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.34.0/dist/tabler-icons.min.css">
<style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Vazirmatn,sans-serif;background:#070b12;color:#edf5ff}
body{display:grid;place-items:center;padding:24px;overflow:hidden}
.bg{position:fixed;inset:0;background:radial-gradient(circle at 15% 15%,rgba(48,132,255,.18),transparent 32%),radial-gradient(circle at 85% 75%,rgba(120,72,255,.14),transparent 30%),linear-gradient(145deg,#070b12,#0b1220 52%,#080c15)}
.grid{position:fixed;inset:0;opacity:.18;background-image:linear-gradient(rgba(120,150,190,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(120,150,190,.12) 1px,transparent 1px);background-size:44px 44px}
.card{position:relative;width:min(430px,100%);padding:34px;border:1px solid #ffffff12;background:#0d1522ed;backdrop-filter:blur(28px);border-radius:28px;box-shadow:0 30px 90px #0009}
.logo{display:flex;align-items:center;gap:12px;margin-bottom:30px}.logo-mark{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:linear-gradient(135deg,#1677ff,#7b5cff);box-shadow:0 12px 30px #1677ff45;font-size:23px}.logo b{font-size:20px}.logo span{display:block;color:#70819a;font-size:11px;margin-top:2px}
h1{font-size:27px;margin:0 0 8px}p{color:#7f91aa;font-size:13px;margin:0 0 25px}
label{display:block;font-size:12px;color:#8fa0b7;margin-bottom:8px}.field{position:relative;margin-bottom:17px}.field i{position:absolute;right:13px;top:13px;color:#637590}.field input{width:100%;height:47px;padding:0 42px 0 14px;border-radius:13px;border:1px solid #ffffff10;background:#08101bd9;color:#fff;outline:none;font:inherit}.field input:focus{border-color:#1677ff88;box-shadow:0 0 0 4px #1677ff12}
button{width:100%;height:48px;border:0;border-radius:13px;background:linear-gradient(135deg,#1677ff,#5b62ff);color:#fff;font:700 13px Vazirmatn;cursor:pointer;box-shadow:0 14px 30px #1677ff30}.err{display:none;margin-bottom:14px;padding:10px 12px;border-radius:11px;background:#ff496d14;border:1px solid #ff496d30;color:#ff829b;font-size:12px}.foot{margin-top:20px;text-align:center;color:#4e6079;font-size:10px}
</style></head>
<body><div class="bg"></div><div class="grid"></div>
<main class="card">
<div class="logo"><div class="logo-mark"><i class="ti ti-brand-xing"></i></div><div><b>CBee Gateway</b><span>Network Control Center</span></div></div>
<h1>خوش آمدید</h1><p>برای ورود به مرکز مدیریت شبکه، رمز عبور مدیر را وارد کنید.</p>
<div id="err" class="err"></div>
<form id="form"><label>رمز عبور</label><div class="field"><i class="ti ti-lock"></i><input id="pw" type="password" autocomplete="current-password" autofocus placeholder="••••••••"></div><button>ورود به پنل <i class="ti ti-arrow-left"></i></button></form>
<div class="foot">CBee Gateway · Secure Administration</div>
</main>
<script>
const f=document.getElementById('form'),e=document.getElementById('err');
f.onsubmit=async ev=>{ev.preventDefault();e.style.display='none';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('pw').value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'رمز عبور اشتباه است');location.href='/Cbee'}catch(x){e.textContent=x.message;e.style.display='block'}};
</script></body></html>'''

DASHBOARD_HTML = r'''<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>CBee Gateway</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.34.0/dist/tabler-icons.min.css">
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<style>
:root{--bg:#070b12;--panel:#0d1420;--panel2:#101a29;--line:#ffffff10;--line2:#ffffff18;--text:#edf5ff;--muted:#7d8da4;--muted2:#56677f;--accent:#3385ff;--accent2:#6b5cff;--good:#21d19a;--warn:#ffbd5c;--bad:#ff5f7d;--radius:20px;--side:260px}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Vazirmatn,sans-serif}body{overflow-x:hidden}
.bgfx{position:fixed;inset:0;pointer-events:none;z-index:0;background:radial-gradient(circle at 80% 5%,rgba(51,133,255,.09),transparent 27%),radial-gradient(circle at 10% 90%,rgba(107,92,255,.07),transparent 30%)}
.bgfx:after{content:"";position:absolute;inset:0;opacity:.12;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:42px 42px}
.sidebar{position:fixed;z-index:50;top:0;bottom:0;right:0;width:var(--side);padding:18px 14px;border-left:1px solid var(--line);background:#09101ae8;backdrop-filter:blur(26px);display:flex;flex-direction:column}
.brand{height:58px;padding:0 8px;display:flex;align-items:center;gap:11px}.brandmark{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 12px 30px rgba(51,133,255,.25);font-size:20px}.brand b{font-size:16px}.brand small{display:block;color:var(--muted2);font-size:9px;margin-top:1px;letter-spacing:.5px}
.side-label{font-size:9px;color:#53647b;padding:19px 10px 7px;text-transform:uppercase;letter-spacing:1.5px}.nav{display:flex;flex-direction:column;gap:4px}.nav button{border:1px solid transparent;background:transparent;color:#8b9bb0;width:100%;height:44px;border-radius:12px;display:flex;align-items:center;gap:11px;padding:0 12px;cursor:pointer;text-align:right;transition:.2s}.nav button i{font-size:18px}.nav button:hover{background:#ffffff06;color:#dce8f7}.nav button.active{color:#fff;background:linear-gradient(90deg,rgba(51,133,255,.18),transparent);border-color:rgba(51,133,255,.24);box-shadow:inset -3px 0 0 var(--accent)}.nav .count{margin-right:auto;background:#ffffff0a;color:#8092ab;padding:2px 7px;border-radius:20px;font-size:9px}.side-bottom{margin-top:auto}.status-mini{border:1px solid var(--line);background:#ffffff04;border-radius:14px;padding:11px;margin-bottom:8px}.status-mini div{display:flex;justify-content:space-between;font-size:10px;color:var(--muted)}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--good);box-shadow:0 0 10px var(--good);margin-left:5px}.logout{width:100%;height:40px;border:1px solid #ffffff0e;background:#ffffff05;color:#8999af;border-radius:11px;cursor:pointer}
.main{position:relative;z-index:1;margin-right:var(--side);width:calc(100% - var(--side));min-width:0;padding:18px 22px 40px}.topbar{height:58px;display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.title h1{margin:0;font-size:20px}.title p{margin:2px 0 0;color:var(--muted);font-size:10px}.tools{display:flex;gap:7px;align-items:center}.tool,.select{height:38px;border:1px solid var(--line2);background:#ffffff06;color:#aebed1;border-radius:11px;padding:0 11px;cursor:pointer}.select{outline:none}.mobile-menu{display:none}
.page{display:none;animation:fade .25s ease}.page.on{display:block}@keyframes fade{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{position:relative;overflow:hidden;min-height:128px;border:1px solid var(--line);background:linear-gradient(145deg,#101a28e8,#0b131fe8);border-radius:var(--radius);padding:17px;box-shadow:0 18px 45px #0002}.stat:before{content:"";position:absolute;width:100px;height:100px;border-radius:50%;right:-30px;top:-45px;background:rgba(51,133,255,.12);filter:blur(20px)}.stat .icon{width:37px;height:37px;border-radius:11px;display:grid;place-items:center;background:rgba(51,133,255,.12);color:var(--accent);font-size:17px}.stat label{display:block;color:var(--muted);font-size:10px;margin-top:14px}.stat strong{font-size:24px;line-height:1.1;display:block;margin-top:3px}.stat em{font-style:normal;color:var(--muted2);font-size:9px}
.two{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(290px,.8fr);gap:12px;margin-top:12px}.panel{border:1px solid var(--line);background:linear-gradient(145deg,#0f1825ed,#0a121ded);border-radius:var(--radius);padding:17px;box-shadow:0 18px 45px #0002}.ph{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.ph b{font-size:12px}.ph span{font-size:9px;color:var(--muted)}.chartbox{height:275px;position:relative}.chartbox canvas{width:100%!important;height:100%!important}
.ring{display:grid;grid-template-columns:140px 1fr;gap:17px;align-items:center}.donut{height:145px}.legend{display:flex;flex-direction:column;gap:11px}.leg{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:10px}.leg b{color:#dbe8f7}.sq{width:8px;height:8px;border-radius:3px;display:inline-block;margin-left:7px}
.activity{display:flex;flex-direction:column;gap:8px}.act{display:flex;gap:9px;align-items:flex-start;padding:9px;border-radius:11px;background:#ffffff03}.act i{width:27px;height:27px;display:grid;place-items:center;border-radius:8px;background:#ffffff07;color:var(--accent);font-size:13px}.act b{display:block;font-size:10px}.act span{display:block;color:var(--muted2);font-size:8px;margin-top:2px}.good{color:var(--good)!important}.bad{color:var(--bad)!important}.warn{color:var(--warn)!important}
.section{margin-top:12px}.toolbar{display:flex;gap:8px;align-items:center;justify-content:space-between;margin-bottom:10px;flex-wrap:wrap}.search{height:40px;min-width:220px;border:1px solid var(--line);background:#ffffff04;color:#fff;border-radius:11px;padding:0 12px;outline:none}.btn{height:40px;border:1px solid var(--line2);border-radius:11px;background:#ffffff06;color:#b6c6d8;padding:0 13px;cursor:pointer}.btn:hover{background:#ffffff0c;color:#fff}.btn.primary{border:0;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;box-shadow:0 10px 25px rgba(51,133,255,.2)}.btn.sm{height:32px;padding:0 9px;font-size:10px}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:15px}.table{width:100%;border-collapse:collapse;min-width:760px}.table th,.table td{padding:12px 11px;border-bottom:1px solid var(--line);text-align:right;font-size:10px;white-space:nowrap}.table th{color:#61738b;font-size:9px;background:#ffffff02}.table td{color:#b9c7d8}.table tr:last-child td{border-bottom:0}.table tr:hover td{background:#ffffff03}.tag{display:inline-flex;padding:3px 7px;border-radius:6px;background:#1677ff12;color:#72adff;font-size:8px;margin-left:3px}
.status{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border-radius:7px;font-size:8px}.status.on{color:var(--good);background:#21d19a10}.status.off{color:var(--bad);background:#ff5f7d10}
.cfg-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cfg{border:1px solid var(--line);background:#ffffff03;border-radius:15px;padding:14px}.cfg-top{display:flex;justify-content:space-between;gap:10px}.cfg-name{font-weight:700;font-size:11px}.cfg-meta{color:var(--muted2);font-size:8px;margin-top:4px;direction:ltr;text-align:right}.bar{height:5px;background:#ffffff08;border-radius:9px;overflow:hidden;margin:12px 0 6px}.bar i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--accent),var(--accent2))}.cfg-foot{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:8px;gap:8px}.actions{display:flex;gap:5px}.iconbtn{width:31px;height:31px;border:1px solid var(--line);background:#ffffff04;color:#8192aa;border-radius:8px;cursor:pointer}.iconbtn:hover{color:#fff;background:#ffffff09}
.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.field{display:flex;flex-direction:column;gap:7px}.field.full{grid-column:1/-1}.field label{font-size:10px;color:#8799b0}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line2);background:#080f19;color:#eaf3ff;border-radius:11px;padding:0 12px;height:42px;outline:none}.field textarea{height:100px;padding-top:10px;resize:vertical}.help{font-size:8px;color:var(--muted2)}.form-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}
.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.setting{border:1px solid var(--line);background:#ffffff03;border-radius:15px;padding:14px}.setting h3{font-size:11px;margin:0 0 12px}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.row:last-child{border-bottom:0}.row span{font-size:9px;color:var(--muted)}.row input,.row select{height:34px;border:1px solid var(--line);background:#080f19;color:#dce8f7;border-radius:9px;padding:0 8px;max-width:220px}.toggle{width:38px;height:22px;border:0;border-radius:20px;background:#253143;position:relative;cursor:pointer}.toggle i{position:absolute;top:3px;right:3px;width:16px;height:16px;background:#7890ac;border-radius:50%;transition:.2s}.toggle.on{background:var(--accent)}.toggle.on i{right:19px;background:#fff}
.empty{text-align:center;padding:35px;color:var(--muted2);font-size:10px}.empty i{font-size:28px;display:block;margin-bottom:8px;color:#3c4e66}
.toast{position:fixed;z-index:100;bottom:20px;left:20px;display:flex;gap:8px;align-items:center;max-width:360px;padding:11px 14px;border:1px solid var(--line2);background:#0d1724ee;backdrop-filter:blur(20px);border-radius:12px;color:#dce9f8;font-size:10px;box-shadow:0 15px 45px #0007;transform:translateY(100px);opacity:0;transition:.25s}.toast.show{transform:none;opacity:1}
.modal{position:fixed;inset:0;z-index:80;background:#0009;display:none;place-items:center;padding:20px}.modal.show{display:grid}.modal-card{width:min(720px,100%);max-height:90vh;overflow:auto;border:1px solid var(--line2);background:#0c1521;backdrop-filter:blur(25px);border-radius:20px;padding:18px;box-shadow:0 30px 100px #000a}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.modal-head b{font-size:13px}.close{border:0;background:#ffffff08;color:#8ca0b8;width:32px;height:32px;border-radius:8px;cursor:pointer}
@media(max-width:1050px){.grid4{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.cfg-grid{grid-template-columns:1fr}}
@media(max-width:780px){:root{--side:0px}.sidebar{width:270px;right:-280px;transition:.25s}.sidebar.open{right:0}.main{margin-right:0;width:100%;padding:12px}.mobile-menu{display:block}.topbar{height:50px}.form-grid,.settings-grid{grid-template-columns:1fr}.grid4{grid-template-columns:1fr 1fr}.stat{min-height:115px;padding:13px}.stat strong{font-size:20px}.ring{grid-template-columns:1fr}.donut{height:190px}.search{min-width:150px;flex:1}}
body.compact .panel,body.compact .stat{padding:11px}body.no-motion *,body.no-motion *:before,body.no-motion *:after{animation:none!important;transition:none!important}
</style></head>
<body>
<div class="bgfx"></div><div class="app">
<aside id="side" class="sidebar">
<div class="brand"><div class="brandmark"><i class="ti ti-brand-xing"></i></div><div><b>CBee Gateway</b><small>NETWORK CONTROL CENTER</small></div></div>
<div class="side-label" data-t="workspace">Workspace</div>
<nav class="nav">
<button class="active" data-page="home"><i class="ti ti-layout-dashboard"></i><span data-t="dashboard">داشبورد</span></button>
<button data-page="create"><i class="ti ti-wand"></i><span data-t="create">ساخت کانفیگ</span></button>
<button data-page="configs"><i class="ti ti-key"></i><span data-t="configs">کانفیگ‌ها</span><span id="nav-count" class="count">0</span></button>
<button data-page="connections"><i class="ti ti-activity"></i><span data-t="connections">اتصالات زنده</span><span id="nav-conn" class="count">0</span></button>
<button data-page="activity"><i class="ti ti-timeline-event"></i><span data-t="activity">رویدادها</span></button>
</nav>
<div class="side-label" data-t="system">System</div><nav class="nav"><button data-page="settings"><i class="ti ti-adjustments"></i><span data-t="settings">تنظیمات</span></button></nav>
<div class="side-bottom"><div class="status-mini"><div><span><i class="dot"></i><span data-t="gateway">Gateway</span></span><b id="api-status" class="good">ONLINE</b></div><div style="margin-top:7px"><span data-t="host">Host</span><b id="side-host">—</b></div></div><button id="logout" class="logout"><i class="ti ti-logout-2"></i> <span data-t="logout">خروج</span></button></div>
</aside>
<main class="main">
<header class="topbar"><div style="display:flex;align-items:center;gap:9px"><button id="mobile-menu" class="tool"><i class="ti ti-menu-2"></i></button><div class="title"><h1 id="page-title">داشبورد</h1><p>نمای زنده از وضعیت Gateway</p></div></div><div class="tools"><select id="lang" class="select"><option value="fa">فارسی</option><option value="en">English</option><option value="tr">Türkçe</option><option value="ar">العربية</option><option value="ru">Русский</option><option value="de">Deutsch</option><option value="fr">Français</option><option value="es">Español</option><option value="zh">中文</option><option value="hi">हिन्दी</option></select><button id="refresh" class="tool"><i class="ti ti-refresh"></i></button></div></header>

<section id="page-home" class="page on">
<div class="grid4">
<div class="stat"><div class="icon"><i class="ti ti-users"></i></div><label data-t="activeClients">کلاینت‌های فعال</label><strong id="s-clients">0</strong><em data-t="uniqueIps">IP یکتا در اتصالات زنده</em></div>
<div class="stat"><div class="icon"><i class="ti ti-key"></i></div><label data-t="configs">کانفیگ‌ها</label><strong id="s-links">0</strong><em id="s-links-sub">0 active</em></div>
<div class="stat"><div class="icon"><i class="ti ti-chart-line"></i></div><label data-t="recordedTraffic">ترافیک ثبت‌شده</label><strong id="s-traffic">0 B</strong><em data-t="gatewayTraffic">از Gateway</em></div>
<div class="stat"><div class="icon"><i class="ti ti-clock"></i></div><label data-t="uptime">Uptime</label><strong id="s-up">00:00:00</strong><em id="s-errors">0 errors</em></div>
</div>
<div class="two"><div class="panel"><div class="ph"><b data-t="trafficChart">نمودار ترافیک ثبت‌شده</b><span>Hourly gateway data</span></div><div class="chartbox"><canvas id="trafficChart"></canvas></div></div>
<div class="panel"><div class="ph"><b data-t="networkState">وضعیت شبکه</b><span id="now"></span></div><div class="ring"><div class="donut"><canvas id="stateChart"></canvas></div><div class="legend"><div class="leg"><span><i class="sq" style="background:#21d19a"></i><span data-t="activeConfigs">کانفیگ فعال</span></span><b id="lg-active">0</b></div><div class="leg"><span><i class="sq" style="background:#ffbd5c"></i><span data-t="expired">منقضی</span></span><b id="lg-exp">0</b></div><div class="leg"><span><i class="sq" style="background:#45566d"></i><span data-t="inactive">غیرفعال</span></span><b id="lg-off">0</b></div></div></div></div></div>
<div class="two"><div class="panel"><div class="ph"><b data-t="liveConnections">اتصالات زنده</b><span id="conn-summary">0</span></div><div id="home-conns" class="activity"></div></div><div class="panel"><div class="ph"><b data-t="recentActivity">آخرین رویدادها</b><span data-t="live">LIVE</span></div><div id="home-activity" class="activity"></div></div></div>
</section>

<section id="page-create" class="page"><div class="panel"><div class="ph"><b data-t="createConfig">ساخت کانفیگ جدید</b><span data-t="generator">Generator</span></div>
<div class="form-grid"><div class="field"><label data-t="label">نام کانفیگ</label><input id="f-label" placeholder="CBee-01"></div><div class="field"><label data-t="protocol">پروتکل</label><select id="f-proto"><option value="vless-ws">VLESS · WebSocket</option><option value="xhttp-packet-up">XHTTP · Packet Up</option><option value="xhttp-stream-up">XHTTP · Stream Up</option><option value="xhttp-stream-one">XHTTP · Stream One</option></select></div>
<div class="field"><label data-t="count">تعداد ساخت</label><input id="f-count" type="number" min="1" max="100" value="1"></div><div class="field"><label data-t="trafficLimit">محدودیت حجم</label><div style="display:grid;grid-template-columns:1fr 100px;gap:7px"><input id="f-limit" type="number" min="0" value="0"><select id="f-unit"><option>GB</option><option>MB</option><option>TB</option></select></div></div>
<div class="field"><label data-t="expiry">انقضا (روز)</label><input id="f-exp" type="number" min="0" value="0"><span class="help" data-t="zeroUnlimited">۰ یعنی بدون انقضا</span></div><div class="field"><label data-t="group">یادداشت</label><input id="f-note"></div>
<div class="field full"><label data-t="ips">IP / Host اختصاصی</label><textarea id="f-ips" placeholder="اگر خالی باشد از تنظیمات سراسری استفاده می‌شود."></textarea></div></div><div class="form-actions"><button id="create-btn" class="btn primary"><i class="ti ti-sparkles"></i> <span data-t="generate">ساخت کانفیگ</span></button></div></div>
<div class="panel section"><div class="ph"><b data-t="lastResult">آخرین خروجی</b><span data-t="copyable">قابل کپی</span></div><textarea id="result" style="width:100%;height:150px;background:#060c14;border:1px solid var(--line);border-radius:12px;color:#a9d0ff;padding:12px;direction:ltr;outline:none" readonly></textarea><div class="form-actions"><button id="copy-result" class="btn"><i class="ti ti-copy"></i> <span data-t="copy">کپی</span></button></div></div></section>

<section id="page-configs" class="page"><div class="toolbar"><input id="cfg-search" class="search" placeholder="جستجوی نام، UUID یا پروتکل"><div style="display:flex;gap:7px"><button id="bulk-toggle" class="btn"><i class="ti ti-stack-2"></i> <span data-t="bulkCreate">ساخت گروهی</span></button><button id="create-go" class="btn primary"><i class="ti ti-plus"></i> <span data-t="newConfig">کانفیگ جدید</span></button></div></div><div id="cfg-grid" class="cfg-grid"></div></section>

<section id="page-connections" class="page"><div class="toolbar"><input id="conn-search" class="search" placeholder="جستجوی IP، کانفیگ یا Transport"><span style="font-size:9px;color:var(--muted)">Active clients = unique IPs</span></div><div class="table-wrap"><table class="table"><thead><tr><th data-t="ip">IP</th><th data-t="sessions">Sessions</th><th data-t="config">کانفیگ</th><th data-t="transport">Transport</th><th data-t="traffic">Traffic</th><th data-t="lastSeen">آخرین وضعیت</th></tr></thead><tbody id="conn-table"></tbody></table></div></section>
<section id="page-activity" class="page"><div class="toolbar"><input id="act-search" class="search" placeholder="جستجوی رویداد"></div><div id="activity-list" class="activity"></div></section>

<section id="page-settings" class="page"><div class="settings-grid">
<div class="setting"><h3><i class="ti ti-server"></i> <span data-t="networkSettings">تنظیمات شبکه</span></h3><div class="row"><span data-t="host">Host</span><b id="set-host" style="font-size:9px;direction:ltr">—</b></div><div class="row"><span data-t="globalIps">IPهای سراسری</span><textarea id="set-ips" style="height:70px;width:220px;border:1px solid var(--line);background:#080f19;color:#fff;border-radius:8px;padding:7px"></textarea></div><div class="row"><span data-t="port">Port</span><input id="set-port" type="number" placeholder="443"></div><div class="row"><span data-t="saveNetwork">ذخیره شبکه</span><button id="save-network" class="btn sm primary">Save</button></div></div>
<div class="setting"><h3><i class="ti ti-palette"></i> <span data-t="appearance">ظاهر</span></h3><div class="row"><span data-t="accent">رنگ اصلی</span><input id="accent" type="color" value="#3385ff" style="width:55px;padding:2px"></div><div class="row"><span data-t="compact">حالت فشرده</span><button id="compact" class="toggle"><i></i></button></div><div class="row"><span data-t="motion">انیمیشن</span><button id="motion" class="toggle on"><i></i></button></div><div class="row"><span data-t="refreshRate">نرخ بروزرسانی</span><select id="rate"><option value="2000">2s</option><option value="3000" selected>3s</option><option value="5000">5s</option><option value="10000">10s</option></select></div></div>
<div class="setting"><h3><i class="ti ti-lock"></i> <span data-t="security">امنیت</span></h3><div class="field"><label data-t="currentPassword">رمز فعلی</label><input id="cp-cur" type="password"></div><div class="field" style="margin-top:8px"><label data-t="newPassword">رمز جدید</label><input id="cp-new" type="password"></div><div class="field" style="margin-top:8px"><label data-t="repeatPassword">تکرار رمز</label><input id="cp-cf" type="password"></div><button id="change-pw" class="btn primary" style="margin-top:10px;width:100%" data-t="changePassword">تغییر رمز</button></div>
<div class="setting"><h3><i class="ti ti-info-circle"></i> <span data-t="about">درباره پنل</span></h3><div class="row"><span>UI</span><b>CBee Premium</b></div><div class="row"><span>API</span><b>/stats · /api/connections</b></div><div class="row"><span data-t="platform">Platform</span><b>Railway ready</b></div></div>
</div></section>
</main></div>

<div id="modal" class="modal"><div class="modal-card"><div class="modal-head"><b>ویرایش کانفیگ</b><button class="close" id="modal-close">×</button></div><div class="form-grid"><input id="m-id" type="hidden"><div class="field"><label>نام</label><input id="m-label"></div><div class="field"><label>حجم</label><div style="display:grid;grid-template-columns:1fr 90px;gap:6px"><input id="m-limit" type="number"><select id="m-unit"><option>GB</option><option>MB</option><option>TB</option></select></div></div><div class="field"><label>انقضا (روز)</label><input id="m-exp" type="number"></div><div class="field"><label>پروتکل</label><select id="m-proto"><option value="vless-ws">VLESS · WebSocket</option><option value="xhttp-packet-up">XHTTP · Packet Up</option><option value="xhttp-stream-up">XHTTP · Stream Up</option><option value="xhttp-stream-one">XHTTP · Stream One</option></select></div><div class="field full"><label>IP</label><textarea id="m-ips"></textarea></div><div class="field full"><label>Note</label><input id="m-note"></div></div><div class="form-actions"><button id="modal-save" class="btn primary">ذخیره</button></div></div></div>
<div id="toast" class="toast"><i class="ti ti-circle-check"></i><span></span></div>

<script>
const T={
fa:{workspace:'فضای کاری',dashboard:'داشبورد',create:'ساخت کانفیگ',configs:'کانفیگ‌ها',connections:'اتصالات زنده',activity:'رویدادها',system:'سیستم',settings:'تنظیمات',logout:'خروج',gateway:'Gateway',host:'Host',activeClients:'کلاینت‌های فعال',uniqueIps:'IP یکتا در اتصالات زنده',recordedTraffic:'ترافیک ثبت‌شده',gatewayTraffic:'از Gateway',uptime:'Uptime',trafficChart:'نمودار ترافیک ثبت‌شده',networkState:'وضعیت شبکه',activeConfigs:'کانفیگ فعال',expired:'منقضی',inactive:'غیرفعال',liveConnections:'اتصالات زنده',recentActivity:'آخرین رویدادها',live:'LIVE',createConfig:'ساخت کانفیگ جدید',generator:'Generator',label:'نام کانفیگ',protocol:'پروتکل',count:'تعداد ساخت',trafficLimit:'محدودیت حجم',expiry:'انقضا (روز)',zeroUnlimited:'۰ یعنی بدون انقضا',group:'یادداشت',ips:'IP / Host اختصاصی',generate:'ساخت کانفیگ',lastResult:'آخرین خروجی',copyable:'قابل کپی',copy:'کپی',bulkCreate:'ساخت گروهی',newConfig:'کانفیگ جدید',ip:'IP',sessions:'Sessions',config:'کانفیگ',transport:'Transport',traffic:'Traffic',lastSeen:'آخرین وضعیت',networkSettings:'تنظیمات شبکه',globalIps:'IPهای سراسری',port:'Port',saveNetwork:'ذخیره شبکه',appearance:'ظاهر',accent:'رنگ اصلی',compact:'حالت فشرده',motion:'انیمیشن',refreshRate:'نرخ بروزرسانی',security:'امنیت',currentPassword:'رمز فعلی',newPassword:'رمز جدید',repeatPassword:'تکرار رمز',changePassword:'تغییر رمز',about:'درباره پنل',platform:'Platform',save:'ذخیره'},
en:{workspace:'Workspace',dashboard:'Dashboard',create:'Create Configs',configs:'Configs',connections:'Live Connections',activity:'Activity',system:'System',settings:'Settings',logout:'Logout',gateway:'Gateway',host:'Host',activeClients:'Active clients',uniqueIps:'Unique IPs in live connections',recordedTraffic:'Recorded traffic',gatewayTraffic:'From Gateway',uptime:'Uptime',trafficChart:'Recorded traffic chart',networkState:'Network state',activeConfigs:'Active configs',expired:'Expired',inactive:'Inactive',liveConnections:'Live connections',recentActivity:'Recent activity',live:'LIVE',createConfig:'Create new config',generator:'Generator',label:'Config name',protocol:'Protocol',count:'Quantity',trafficLimit:'Traffic limit',expiry:'Expiry (days)',zeroUnlimited:'0 means unlimited',group:'Note',ips:'Dedicated IP / Host',generate:'Generate config',lastResult:'Last output',copyable:'Copyable',copy:'Copy',bulkCreate:'Bulk create',newConfig:'New config',ip:'IP',sessions:'Sessions',config:'Config',transport:'Transport',traffic:'Traffic',lastSeen:'Last status',networkSettings:'Network settings',globalIps:'Global IPs',port:'Port',saveNetwork:'Save network',appearance:'Appearance',accent:'Accent color',compact:'Compact mode',motion:'Animations',refreshRate:'Refresh rate',security:'Security',currentPassword:'Current password',newPassword:'New password',repeatPassword:'Repeat password',changePassword:'Change password',about:'About',platform:'Platform',save:'Save'},
tr:{workspace:'Çalışma alanı',dashboard:'Gösterge Paneli',create:'Yapılandırma oluştur',configs:'Yapılandırmalar',connections:'Canlı bağlantılar',activity:'Etkinlik',system:'Sistem',settings:'Ayarlar',logout:'Çıkış',gateway:'Gateway',host:'Host',activeClients:'Aktif istemciler',uniqueIps:'Benzersiz IP',recordedTraffic:'Kaydedilen trafik',gatewayTraffic:'Gateway',uptime:'Çalışma süresi',trafficChart:'Trafik grafiği',networkState:'Ağ durumu',activeConfigs:'Aktif yapılandırmalar',expired:'Süresi dolmuş',inactive:'Pasif',liveConnections:'Canlı bağlantılar',recentActivity:'Son etkinlik',live:'CANLI',createConfig:'Yeni yapılandırma',generator:'Oluşturucu',label:'Yapılandırma adı',protocol:'Protokol',count:'Miktar',trafficLimit:'Trafik limiti',expiry:'Süre (gün)',zeroUnlimited:'0 sınırsız',group:'Not',ips:'Özel IP / Host',generate:'Oluştur',lastResult:'Son çıktı',copyable:'Kopyalanabilir',copy:'Kopyala',bulkCreate:'Toplu oluştur',newConfig:'Yeni yapılandırma',ip:'IP',sessions:'Oturumlar',config:'Yapılandırma',transport:'Transport',traffic:'Trafik',lastSeen:'Son durum',networkSettings:'Ağ ayarları',globalIps:'Genel IPler',port:'Port',saveNetwork:'Ağı kaydet',appearance:'Görünüm',accent:'Vurgu rengi',compact:'Kompakt',motion:'Animasyon',refreshRate:'Yenileme',security:'Güvenlik',currentPassword:'Mevcut şifre',newPassword:'Yeni şifre',repeatPassword:'Tekrar',changePassword:'Şifreyi değiştir',about:'Hakkında',platform:'Platform',save:'Kaydet'},
ar:{workspace:'مساحة العمل',dashboard:'لوحة التحكم',create:'إنشاء إعداد',configs:'الإعدادات',connections:'الاتصالات الحية',activity:'النشاط',system:'النظام',settings:'الإعدادات',logout:'تسجيل الخروج',gateway:'البوابة',host:'المضيف',activeClients:'العملاء النشطون',uniqueIps:'عناوين IP الفريدة',recordedTraffic:'حركة المرور المسجلة',gatewayTraffic:'من البوابة',uptime:'وقت التشغيل',trafficChart:'مخطط حركة المرور',networkState:'حالة الشبكة',activeConfigs:'الإعدادات النشطة',expired:'منتهية',inactive:'غير نشطة',liveConnections:'الاتصالات الحية',recentActivity:'النشاط الأخير',live:'مباشر',createConfig:'إنشاء إعداد جديد',generator:'مولد',label:'اسم الإعداد',protocol:'البروتوكول',count:'العدد',trafficLimit:'حد البيانات',expiry:'الانتهاء بالأيام',zeroUnlimited:'0 بدون انتهاء',group:'ملاحظة',ips:'IP / Host مخصص',generate:'إنشاء',lastResult:'آخر نتيجة',copyable:'قابل للنسخ',copy:'نسخ',bulkCreate:'إنشاء جماعي',newConfig:'إعداد جديد',ip:'IP',sessions:'جلسات',config:'إعداد',transport:'النقل',traffic:'البيانات',lastSeen:'آخر حالة',networkSettings:'إعدادات الشبكة',globalIps:'عناوين IP العامة',port:'المنفذ',saveNetwork:'حفظ الشبكة',appearance:'المظهر',accent:'اللون',compact:'مضغوط',motion:'الحركة',refreshRate:'معدل التحديث',security:'الأمان',currentPassword:'كلمة المرور الحالية',newPassword:'كلمة المرور الجديدة',repeatPassword:'التكرار',changePassword:'تغيير كلمة المرور',about:'حول',platform:'المنصة',save:'حفظ'},
ru:{workspace:'Рабочая область',dashboard:'Панель',create:'Создать конфиг',configs:'Конфиги',connections:'Активные подключения',activity:'События',system:'Система',settings:'Настройки',logout:'Выйти',gateway:'Шлюз',host:'Хост',activeClients:'Активные клиенты',uniqueIps:'Уникальные IP',recordedTraffic:'Записанный трафик',gatewayTraffic:'Из Gateway',uptime:'Аптайм',trafficChart:'График трафика',networkState:'Состояние сети',activeConfigs:'Активные конфиги',expired:'Истёкшие',inactive:'Неактивные',liveConnections:'Активные подключения',recentActivity:'Последние события',live:'LIVE',createConfig:'Создать конфигурацию',generator:'Генератор',label:'Имя',protocol:'Протокол',count:'Количество',trafficLimit:'Лимит трафика',expiry:'Срок (дни)',zeroUnlimited:'0 = без срока',group:'Заметка',ips:'IP / Host',generate:'Создать',lastResult:'Последний результат',copyable:'Можно копировать',copy:'Копировать',bulkCreate:'Массовое создание',newConfig:'Новый конфиг',ip:'IP',sessions:'Сессии',config:'Конфиг',transport:'Транспорт',traffic:'Трафик',lastSeen:'Последнее состояние',networkSettings:'Сеть',globalIps:'Глобальные IP',port:'Порт',saveNetwork:'Сохранить',appearance:'Внешний вид',accent:'Цвет',compact:'Компактный режим',motion:'Анимации',refreshRate:'Обновление',security:'Безопасность',currentPassword:'Текущий пароль',newPassword:'Новый пароль',repeatPassword:'Повтор',changePassword:'Изменить пароль',about:'О панели',platform:'Платформа',save:'Сохранить'},
de:{workspace:'Arbeitsbereich',dashboard:'Dashboard',create:'Konfiguration erstellen',configs:'Konfigurationen',connections:'Live-Verbindungen',activity:'Aktivität',system:'System',settings:'Einstellungen',logout:'Abmelden',gateway:'Gateway',host:'Host',activeClients:'Aktive Clients',uniqueIps:'Eindeutige IPs',recordedTraffic:'Aufgezeichneter Traffic',gatewayTraffic:'Vom Gateway',uptime:'Uptime',trafficChart:'Traffic-Diagramm',networkState:'Netzwerkstatus',activeConfigs:'Aktive Konfigurationen',expired:'Abgelaufen',inactive:'Inaktiv',liveConnections:'Live-Verbindungen',recentActivity:'Letzte Aktivitäten',live:'LIVE',createConfig:'Neue Konfiguration',generator:'Generator',label:'Name',protocol:'Protokoll',count:'Anzahl',trafficLimit:'Traffic-Limit',expiry:'Ablauf (Tage)',zeroUnlimited:'0 = unbegrenzt',group:'Notiz',ips:'IP / Host',generate:'Erstellen',lastResult:'Letzte Ausgabe',copyable:'Kopierbar',copy:'Kopieren',bulkCreate:'Massen-Erstellung',newConfig:'Neue Konfiguration',ip:'IP',sessions:'Sitzungen',config:'Konfiguration',transport:'Transport',traffic:'Traffic',lastSeen:'Letzter Status',networkSettings:'Netzwerk',globalIps:'Globale IPs',port:'Port',saveNetwork:'Speichern',appearance:'Darstellung',accent:'Akzentfarbe',compact:'Kompakt',motion:'Animationen',refreshRate:'Aktualisierung',security:'Sicherheit',currentPassword:'Aktuelles Passwort',newPassword:'Neues Passwort',repeatPassword:'Wiederholen',changePassword:'Passwort ändern',about:'Über',platform:'Plattform',save:'Speichern'},
fr:{workspace:'Espace de travail',dashboard:'Tableau de bord',create:'Créer une config',configs:'Configurations',connections:'Connexions actives',activity:'Activité',system:'Système',settings:'Paramètres',logout:'Déconnexion',gateway:'Passerelle',host:'Hôte',activeClients:'Clients actifs',uniqueIps:'IPs uniques',recordedTraffic:'Trafic enregistré',gatewayTraffic:'Depuis Gateway',uptime:'Disponibilité',trafficChart:'Graphique du trafic',networkState:'État réseau',activeConfigs:'Configs actives',expired:'Expirées',inactive:'Inactives',liveConnections:'Connexions actives',recentActivity:'Activité récente',live:'LIVE',createConfig:'Créer une configuration',generator:'Générateur',label:'Nom',protocol:'Protocole',count:'Quantité',trafficLimit:'Limite de trafic',expiry:'Expiration (jours)',zeroUnlimited:'0 = illimité',group:'Note',ips:'IP / Host',generate:'Créer',lastResult:'Dernière sortie',copyable:'Copiable',copy:'Copier',bulkCreate:'Création groupée',newConfig:'Nouvelle config',ip:'IP',sessions:'Sessions',config:'Config',transport:'Transport',traffic:'Trafic',lastSeen:'Dernier état',networkSettings:'Réseau',globalIps:'IPs globales',port:'Port',saveNetwork:'Enregistrer',appearance:'Apparence',accent:'Couleur',compact:'Compact',motion:'Animations',refreshRate:'Actualisation',security:'Sécurité',currentPassword:'Mot de passe actuel',newPassword:'Nouveau mot de passe',repeatPassword:'Répéter',changePassword:'Changer le mot de passe',about:'À propos',platform:'Plateforme',save:'Enregistrer'},
es:{workspace:'Espacio de trabajo',dashboard:'Panel',create:'Crear configuración',configs:'Configuraciones',connections:'Conexiones activas',activity:'Actividad',system:'Sistema',settings:'Ajustes',logout:'Salir',gateway:'Gateway',host:'Host',activeClients:'Clientes activos',uniqueIps:'IPs únicas',recordedTraffic:'Tráfico registrado',gatewayTraffic:'Desde Gateway',uptime:'Tiempo activo',trafficChart:'Gráfico de tráfico',networkState:'Estado de red',activeConfigs:'Configs activas',expired:'Expiradas',inactive:'Inactivas',liveConnections:'Conexiones activas',recentActivity:'Actividad reciente',live:'LIVE',createConfig:'Crear configuración',generator:'Generador',label:'Nombre',protocol:'Protocolo',count:'Cantidad',trafficLimit:'Límite de tráfico',expiry:'Expiración (días)',zeroUnlimited:'0 = ilimitado',group:'Nota',ips:'IP / Host',generate:'Crear',lastResult:'Última salida',copyable:'Copiable',copy:'Copiar',bulkCreate:'Creación masiva',newConfig:'Nueva configuración',ip:'IP',sessions:'Sesiones',config:'Config',transport:'Transporte',traffic:'Tráfico',lastSeen:'Último estado',networkSettings:'Red',globalIps:'IPs globales',port:'Puerto',saveNetwork:'Guardar',appearance:'Apariencia',accent:'Color',compact:'Compacto',motion:'Animaciones',refreshRate:'Actualización',security:'Seguridad',currentPassword:'Contraseña actual',newPassword:'Nueva contraseña',repeatPassword:'Repetir',changePassword:'Cambiar contraseña',about:'Acerca de',platform:'Plataforma',save:'Guardar'},
zh:{workspace:'工作区',dashboard:'仪表盘',create:'创建配置',configs:'配置',connections:'实时连接',activity:'活动',system:'系统',settings:'设置',logout:'退出',gateway:'网关',host:'主机',activeClients:'活跃客户端',uniqueIps:'唯一 IP',recordedTraffic:'已记录流量',gatewayTraffic:'来自网关',uptime:'运行时间',trafficChart:'流量图表',networkState:'网络状态',activeConfigs:'活跃配置',expired:'已过期',inactive:'未启用',liveConnections:'实时连接',recentActivity:'最近活动',live:'实时',createConfig:'创建新配置',generator:'生成器',label:'配置名称',protocol:'协议',count:'数量',trafficLimit:'流量限制',expiry:'过期天数',zeroUnlimited:'0 = 不限',group:'备注',ips:'IP / Host',generate:'创建',lastResult:'最新输出',copyable:'可复制',copy:'复制',bulkCreate:'批量创建',newConfig:'新配置',ip:'IP',sessions:'会话',config:'配置',transport:'传输',traffic:'流量',lastSeen:'最后状态',networkSettings:'网络设置',globalIps:'全局 IP',port:'端口',saveNetwork:'保存网络',appearance:'外观',accent:'主题色',compact:'紧凑模式',motion:'动画',refreshRate:'刷新频率',security:'安全',currentPassword:'当前密码',newPassword:'新密码',repeatPassword:'重复密码',changePassword:'修改密码',about:'关于',platform:'平台',save:'保存'},
hi:{workspace:'वर्कस्पेस',dashboard:'डैशबोर्ड',create:'कॉन्फ़िग बनाएं',configs:'कॉन्फ़िग',connections:'लाइव कनेक्शन',activity:'गतिविधि',system:'सिस्टम',settings:'सेटिंग्स',logout:'लॉगआउट',gateway:'गेटवे',host:'होस्ट',activeClients:'सक्रिय क्लाइंट',uniqueIps:'यूनिक IP',recordedTraffic:'रिकॉर्डेड ट्रैफिक',gatewayTraffic:'Gateway से',uptime:'अपटाइम',trafficChart:'ट्रैफिक चार्ट',networkState:'नेटवर्क स्थिति',activeConfigs:'सक्रिय कॉन्फ़िग',expired:'समाप्त',inactive:'निष्क्रिय',liveConnections:'लाइव कनेक्शन',recentActivity:'हाल की गतिविधि',live:'LIVE',createConfig:'नई कॉन्फ़िग बनाएं',generator:'जनरेटर',label:'नाम',protocol:'प्रोटोकॉल',count:'मात्रा',trafficLimit:'ट्रैफिक सीमा',expiry:'समाप्ति (दिन)',zeroUnlimited:'0 = असीमित',group:'नोट',ips:'IP / Host',generate:'बनाएं',lastResult:'अंतिम आउटपुट',copyable:'कॉपी योग्य',copy:'कॉपी',bulkCreate:'बल्क बनाएं',newConfig:'नई कॉन्फ़िग',ip:'IP',sessions:'सेशन',config:'कॉन्फ़िग',transport:'ट्रांसपोर्ट',traffic:'ट्रैफिक',lastSeen:'अंतिम स्थिति',networkSettings:'नेटवर्क',globalIps:'ग्लोबल IP',port:'पोर्ट',saveNetwork:'सेव नेटवर्क',appearance:'दिखावट',accent:'एक्सेंट रंग',compact:'कॉम्पैक्ट',motion:'एनिमेशन',refreshRate:'रिफ्रेश',security:'सुरक्षा',currentPassword:'वर्तमान पासवर्ड',newPassword:'नया पासवर्ड',repeatPassword:'दोहराएं',changePassword:'पासवर्ड बदलें',about:'जानकारी',platform:'प्लेटफ़ॉर्म',save:'सेव'}
};
const $=id=>document.getElementById(id);
const S={lang:localStorage.cbeeLang||'fa',rate:+localStorage.cbeeRate||3000,motion:localStorage.cbeeMotion!=='0',compact:localStorage.cbeeCompact==='1',stats:null,links:[],conns:[],logs:[]};
let trafficChart,stateChart,timer,activePage='home',editing=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(b){b=Number(b)||0;const u=['B','KB','MB','GB','TB'];let i=0;while(b>=1024&&i<4){b/=1024;i++}return `${b<10&&i?b.toFixed(2):b.toFixed(i?1:0)} ${u[i]}`}
function ago(x){if(!x)return '—';const d=Math.max(0,Math.floor((Date.now()-new Date(x).getTime())/1000));if(d<60)return d+'s';if(d<3600)return Math.floor(d/60)+'m';return Math.floor(d/3600)+'h'}
function toast(msg,type='ok'){const t=$('toast');t.className='toast '+type+' show';t.querySelector('span').textContent=msg;setTimeout(()=>t.classList.remove('show'),2600)}
async function api(url,opt={}){const r=await fetch(url,opt);if(r.status===401){location='/login';throw Error('Unauthorized')}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Request failed');return d}
function applyLang(){const v=T[S.lang]||T.en;document.documentElement.lang=S.lang;document.documentElement.dir=['fa','ar'].includes(S.lang)?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(e=>{if(v[e.dataset.t])e.textContent=v[e.dataset.t]});$('lang').value=S.lang;localStorage.cbeeLang=S.lang}
function page(p){activePage=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$('page-'+p).classList.add('on');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const v=T[S.lang]||T.en;$('page-title').textContent=p==='home'?v.dashboard:(v[p]||p);if(innerWidth<781)$('side').classList.remove('open');if(p==='configs')renderConfigs();if(p==='connections')renderConnections();if(p==='activity')renderActivity()}
function setTheme(){document.documentElement.style.setProperty('--accent',localStorage.cbeeAccent||'#3385ff');document.body.classList.toggle('compact',S.compact);document.body.classList.toggle('no-motion',!S.motion);$('accent').value=localStorage.cbeeAccent||'#3385ff';$('compact').classList.toggle('on',S.compact);$('motion').classList.toggle('on',S.motion)}
function updateCharts(){const st=S.stats||{},h=Object.entries(st.hourly||{}).sort((a,b)=>a[0].localeCompare(b[0])),labels=h.map(x=>x[0]),data=h.map(x=>Number(x[1])||0);if(trafficChart)trafficChart.destroy();const c=$('trafficChart').getContext('2d'),g=c.createLinearGradient(0,0,0,260);g.addColorStop(0,'rgba(51,133,255,.30)');g.addColorStop(1,'rgba(51,133,255,0)');trafficChart=new Chart(c,{type:'line',data:{labels,datasets:[{data,borderColor:'#4b98ff',backgroundColor:g,fill:true,tension:.42,pointRadius:2,pointHoverRadius:5,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{display:false},tooltip:{callbacks:{label:x=>fmt(x.raw)}}},scales:{x:{grid:{display:false},ticks:{color:'#62738b',font:{size:9},maxTicksLimit:10}},y:{grid:{color:'#ffffff08'},ticks:{color:'#62738b',font:{size:9},callback:v=>fmt(v)}}}}});const a=Number(st.active_links)||0,e=Number(st.expired_links)||0,o=Math.max(0,(Number(st.links_count)||0)-a-e);if(stateChart)stateChart.destroy();stateChart=new Chart($('stateChart'),{type:'doughnut',data:{labels:['Active','Expired','Inactive'],datasets:[{data:[a,e,o],backgroundColor:['#21d19a','#ffbd5c','#45566d'],borderWidth:0}]},options:{cutout:'75%',plugins:{legend:{display:false}}}});$('lg-active').textContent=a;$('lg-exp').textContent=e;$('lg-off').textContent=o}
function renderHome(){const st=S.stats||{},clients=S.conns.length;$('s-clients').textContent=clients;$('nav-conn').textContent=clients;$('s-links').textContent=st.links_count??0;$('nav-count').textContent=st.links_count??0;$('s-links-sub').textContent=(st.active_links??0)+' active';$('s-traffic').textContent=fmt((Number(st.total_traffic_mb)||0)*1048576);$('s-up').textContent=st.uptime||'00:00:00';$('s-errors').textContent=(st.total_errors||0)+' errors';$('conn-summary').textContent=clients+' clients';$('side-host').textContent=location.host;$('set-host').textContent=location.host;$('now').textContent=new Date().toLocaleTimeString(S.lang);const con=S.conns.slice(0,5);$('home-conns').innerHTML=con.length?con.map(c=>`<div class="act"><i class="ti ti-world"></i><div style="flex:1"><b style="direction:ltr;text-align:right">${esc(c.ip)}</b><span>${esc(c.label||'—')} · ${esc((c.transports||[]).join(', '))}</span></div><span class="good">${ago(c.last_connected_at)}</span></div>`).join(''):'<div class="empty"><i class="ti ti-plug-off"></i>No live clients</div>';const logs=S.logs.slice(-5).reverse();$('home-activity').innerHTML=logs.length?logs.map(x=>`<div class="act"><i class="ti ti-bolt"></i><div style="flex:1"><b>${esc(x.message)}</b><span>${esc(x.kind||'system')} · ${ago(x.time)}</span></div></div>`).join(''):'<div class="empty">No events</div>';updateCharts()}
function renderConfigs(){const q=($('cfg-search').value||'').trim().toLowerCase(),a=S.links.filter(x=>(x.label+' '+x.uuid+' '+(x.protocols||[]).join(' ')).toLowerCase().includes(q));$('cfg-grid').innerHTML=a.length?a.map(l=>{const used=Number(l.used_bytes)||0,lim=Number(l.limit_bytes)||0,pct=lim?Math.min(100,used/lim*100):0,on=l.active&&!l.expired;return `<div class="cfg"><div class="cfg-top"><div><div class="cfg-name">${esc(l.label)}</div><div class="cfg-meta">${esc(l.uuid)}</div></div><span class="status ${on?'on':'off'}">${on?'ACTIVE':'OFF'}</span></div><div class="bar"><i style="width:${pct}%"></i></div><div class="cfg-foot"><span>${fmt(used)} / ${lim?fmt(lim):'∞'}</span><span>${(l.protocols||[]).map(p=>`<span class="tag">${esc(p)}</span>`).join('')}</span><div class="actions"><button class="iconbtn" onclick="copy('${esc(l.vless_link)}')"><i class="ti ti-copy"></i></button><button class="iconbtn" onclick="editConfig('${l.uuid}')"><i class="ti ti-pencil"></i></button><button class="iconbtn" onclick="toggleConfig('${l.uuid}',${!l.active})"><i class="ti ti-power"></i></button><button class="iconbtn" onclick="deleteConfig('${l.uuid}')"><i class="ti ti-trash"></i></button></div></div></div>`}).join(''):'<div class="empty" style="grid-column:1/-1"><i class="ti ti-key-off"></i>No configs</div>'}
function renderConnections(){const q=($('conn-search').value||'').toLowerCase(),a=S.conns.filter(x=>(x.ip+' '+x.label+' '+(x.transports||[]).join(' ')).toLowerCase().includes(q));$('conn-table').innerHTML=a.length?a.map(x=>`<tr><td style="direction:ltr">${esc(x.ip)}</td><td>${x.sessions||1}</td><td>${esc(x.label||'—')}</td><td>${(x.transports||[]).map(y=>`<span class="tag">${esc(y)}</span>`).join('')}</td><td>${esc(x.bytes_fmt||fmt(x.bytes))}</td><td>${ago(x.last_connected_at)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No live connections</div></td></tr>'}
function renderActivity(){const q=($('act-search').value||'').toLowerCase(),a=S.logs.filter(x=>(x.message+' '+x.kind+' '+x.level).toLowerCase().includes(q)).slice().reverse();$('activity-list').innerHTML=a.length?a.map(x=>`<div class="act"><i class="ti ti-activity"></i><div style="flex:1"><b>${esc(x.message)}</b><span>${esc(x.kind||'system')} · ${new Date(x.time).toLocaleString(S.lang)}</span></div><span class="${x.level==='err'?'bad':x.level==='warn'?'warn':'good'}">${esc(x.level||'info')}</span></div>`).join(''):'<div class="empty"><i class="ti ti-timeline-event"></i>No activity</div>'}
async function load(){try{const [st,ac,lk,co,gs]=await Promise.all([api('/stats'),api('/api/activity'),api('/api/links'),api('/api/connections'),api('/api/settings/global-ips')]);S.stats=st;S.logs=ac.logs||[];S.links=lk.links||[];S.conns=co.connections||[];$('set-ips').value=(gs.ips||[]).join('\\n');$('set-port').value=gs.port||'';$('api-status').textContent='ONLINE';$('api-status').className='good';renderHome();if(activePage==='configs')renderConfigs();if(activePage==='connections')renderConnections();if(activePage==='activity')renderActivity()}catch(e){$('api-status').textContent='OFFLINE';$('api-status').className='bad'}}
function start(){clearInterval(timer);timer=setInterval(load,S.rate)}
async function createConfig(){const label=$('f-label').value.trim()||'CBee',count=Math.max(1,Math.min(100,+$('f-count').value||1)),body={label,limit_value:+$('f-limit').value||0,limit_unit:$('f-unit').value,expires_days:+$('f-exp').value||0,note:$('f-note').value,protocols:[$('f-proto').value],count},ips=$('f-ips').value.split(/[\\n,]+/).map(x=>x.trim()).filter(Boolean);if(ips.length)body.ips=ips;try{const d=count>1?await api('/api/links/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}):await api('/api/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('result').value=d.vless_link||d.vless_bulk||d.sub_url||'';await copy($('result').value);toast(count+' config'+(count>1?'s':'')+' created');await load()}catch(e){toast(e.message,'err')}}
async function copy(v){if(!v)return;try{await navigator.clipboard.writeText(v);toast('Copied')}catch(e){$('result').value=v;toast('Copy failed','err')}}
async function toggleConfig(id,on){try{await api('/api/links/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:on})});toast(on?'Enabled':'Disabled');await load()}catch(e){toast(e.message,'err')}}
async function deleteConfig(id){if(!confirm('Delete this config?'))return;try{await api('/api/links/'+id,{method:'DELETE'});toast('Deleted');await load()}catch(e){toast(e.message,'err')}}
function editConfig(id){const x=S.links.find(v=>v.uuid===id);if(!x)return;editing=id;$('m-id').value=id;$('m-label').value=x.label||'';$('m-limit').value=x.limit_bytes?((x.limit_bytes/1073741824).toFixed(2)):0;$('m-unit').value='GB';$('m-exp').value=x.expires_at?Math.max(0,Math.ceil((new Date(x.expires_at)-Date.now())/86400000)):0;$('m-proto').value=(x.protocols||['vless-ws'])[0];$('m-ips').value=(x.ips||[]).join('\\n');$('m-note').value=x.note||'';$('modal').classList.add('show')}
async function saveEdit(){if(!editing)return;const body={label:$('m-label').value.trim(),limit_value:+$('m-limit').value||0,limit_unit:$('m-unit').value,expires_days:+$('m-exp').value||0,protocols:[$('m-proto').value],ips:$('m-ips').value.split(/[\\n,]+/).map(x=>x.trim()).filter(Boolean),note:$('m-note').value};try{await api('/api/links/'+editing,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('modal').classList.remove('show');editing=null;toast('Saved');await load()}catch(e){toast(e.message,'err')}}
async function saveNetwork(){const ips=$('set-ips').value.split(/[\\n,]+/).map(x=>x.trim()).filter(Boolean);try{await api('/api/settings/global-ips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ips,port:+$('set-port').value||null})});toast('Network settings saved');await load()}catch(e){toast(e.message,'err')}}
async function changePassword(){const current=$('cp-cur').value,nw=$('cp-new').value,cf=$('cp-cf').value;if(!current||!nw||nw!==cf)return toast('Password fields are invalid','err');try{await api('/api/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_password:current,new_password:nw})});['cp-cur','cp-new','cp-cf'].forEach(id=>$(id).value='');toast('Password changed')}catch(e){toast(e.message,'err')}}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('mobile-menu').onclick=()=>$('side').classList.toggle('open');$('refresh').onclick=()=>load();$('logout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location='/login'};
$('lang').onchange=e=>{S.lang=e.target.value;applyLang();page(activePage);renderHome();renderConfigs();renderConnections();renderActivity()};$('cfg-search').oninput=renderConfigs;$('conn-search').oninput=renderConnections;$('act-search').oninput=renderActivity;
$('create-go').onclick=()=>page('create');$('bulk-toggle').onclick=()=>page('create');$('create-btn').onclick=createConfig;$('copy-result').onclick=()=>copy($('result').value);$('modal-close').onclick=()=>{$('modal').classList.remove('show');editing=null};$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('show')};$('modal-save').onclick=saveEdit;$('save-network').onclick=saveNetwork;$('change-pw').onclick=changePassword;
$('accent').oninput=e=>{localStorage.cbeeAccent=e.target.value;setTheme()};$('compact').onclick=()=>{S.compact=!S.compact;localStorage.cbeeCompact=S.compact?'1':'0';setTheme()};$('motion').onclick=()=>{S.motion=!S.motion;localStorage.cbeeMotion=S.motion?'1':'0';setTheme()};$('rate').onchange=e=>{S.rate=+e.target.value;localStorage.cbeeRate=S.rate;start()};
applyLang();setTheme();$('rate').value=S.rate;load();start();
</script></body></html>'''
